### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by theriturajps** [AKAspanion/chat-app#1]
broo i want to contact you, its urgent, pleace help

**Comment by theriturajps** [comment]
How to i deploy it with configuration

**Comment by AKAspanion** [comment]
Hey @theriturajps 
I deployed the server in Heroku(you can use any other cloud server).
Once you get the deployed server URL.

You can modify this URL with your own.
https://github.com/AKAspanion/chat-app/blob/master/client/src/app/index.tsx#L17

And then the client can be deployed.
